# Build settings
plugins:
  - jekyll-remote-theme

remote_theme: victorangeloblancada/adam

# Remove the next line for your own use
baseurl: adam

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# permalink: /blog/:title/
